name: ci-get-client
on:
  push:
    branches:
    - master
    paths:
    - 'get-client/*'
    - '.github/workflows/ci-get-client.yaml'

jobs:

#building app
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        SHA=${GITHUB_SHA:0:7}
        APP=${GITHUB_REPOSITORY#*/}
        DOCKER_URL=${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPO }}/${APP}/${APP}-get-client:${SHA}
        cd get_client
        docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker build . --no-cache -f Dockerfile -t ${DOCKER_URL}
        docker push ${DOCKER_URL}

#deploy to Kubernetes       
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
      id: setcontext
    - name: Set Portal Secret
      uses: azure/k8s-create-secret@v1
      with:
        namespace: 'default'
        secret-type: 'generic'
        arguments:  --from-literal=url=${{ secrets.PORTAL_URL }} --from-literal=token=${{ secrets.PORTAL_TOKEN }}
        secret-name: portal-credentials   
    - name: Deploy
      run: |
        SHA=${GITHUB_SHA:0:7}
        APP=${GITHUB_REPOSITORY#*/}
        DOCKER_URL=${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_REPO }}/${APP}/${APP}-get-client:${SHA}
        cd get_client
        sed -i "s,IMG,${DOCKER_URL},g" deployment.yaml
        kubectl apply -f deployment.yaml

        

